options:
    kernel-parameters:
        description: semi-colon separated list of paramters in the style accepted by sysctl.conf. No quotes needed, even in case of multiple parameters.
        type: string
