#!/bin/bash -eu

FILE=/etc/sysctl.d/90-kernel-parameters-charm
PARAMS=`config-get kernel-parameters`

for param in $PARAMS; do
    echo "* Setting Kernel Parameter: $param"
    sysctl -w $param
    echo $param >> $FILE
done

exit 0
