#!/bin/bash -eu

FILE=/etc/sysctl.d/90-kernel-parameters-charm
param=""
PARAMS=$(config-get kernel-parameters)
PARAM_SEP=';'

# Sanitize string, remove trailing and leading blanks
PARAMS=$(echo -e "${PARAMS}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

if [[ -z $PARAMS ]]; then
    exit 0
else
    if [ -e $FILE ]; then
	rm $FILE ; touch $FILE
    fi
fi

while [[ ${#PARAMS} -gt 0 ]]; do
    if [[ $PARAMS =~ $PARAM_SEP ]]; then
        param=${PARAMS%%;*}
        PARAMS=${PARAMS#*;}
    else
        param=${PARAMS}
        PARAMS=""
    fi
    param="$(echo -e "${param}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*=[[:space:]]*/=/' -e 's/[[:space:]]*$//')"
    echo "* Setting Kernel Parameter in ${FILE}: ${param}"
    echo "$param" >> $FILE
done
echo "*** Setting Parameters in running Kernel"
sysctl -p $FILE

exit 0
